name: klocalizations_flutter
description: Wrapper around flutter_localizations, with some extra functionality and abstracting some of the common logic. 
version: 0.0.9
homepage: https://github.com/raoulsson/klocalizations_flutter # forked from https://github.com/nombrekeff/klocalizations_flutter

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.29.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.24.8
